/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/../scene_2.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.52}>
        <group position={[1.57, -0.63, 0]}>
          <mesh geometry={nodes.Alabama_0.geometry} material={materials.Dark_green} />
        </group>
        <group position={[-3.87, -2.84, 0]}>
          <mesh geometry={nodes.Alaska_0.geometry} material={materials.Orange} />
        </group>
        <group position={[-3.07, 0.07, 0]}>
          <mesh geometry={nodes.Arizona_0.geometry} material={materials.Yellow} />
        </group>
        <group position={[0.36, -0.35, 0]}>
          <mesh geometry={nodes.Arkansas_0.geometry} material={materials.Orange} />
        </group>
        <group position={[-4.48, 1.57, 0]}>
          <mesh geometry={nodes.California_0.geometry} material={materials.Dark_green} />
        </group>
        <group position={[-2.09, 0.81, 0]}>
          <mesh geometry={nodes.Colorado_0.geometry} material={materials.Orange} />
        </group>
        <group position={[3.83, 1.33, 0]}>
          <mesh geometry={nodes.Connecticut_0.geometry} material={materials.Yellow} />
        </group>
        <group position={[3.57, 0.73, 0]}>
          <mesh geometry={nodes.Delaware_0.geometry} material={materials.Light_Green} />
        </group>
        <group position={[1.73, -1.53, 0]}>
          <mesh geometry={nodes.Florida_0.geometry} material={materials.Yellow} />
        </group>
        <group position={[2.03, -0.6, 0]}>
          <mesh geometry={nodes.Georgia_0.geometry} material={materials.shit} />
        </group>
        <group position={[-1.74, -2.46, 0]}>
          <mesh geometry={nodes.Hawaii_0.geometry} material={materials.shit} />
        </group>
        <group position={[-3, 2.8, 0]}>
          <mesh geometry={nodes.Idaho_0.geometry} material={materials.Yellow} />
        </group>
        <group position={[1.02, 1.02, 0]}>
          <mesh geometry={nodes.Illinois_0.geometry} material={materials.shit} />
        </group>
        <group position={[1.67, 0.91, 0]}>
          <mesh geometry={nodes.indiana_0.geometry} material={materials.Dark_green} />
        </group>
        <group position={[0.02, 1.24, 0]}>
          <mesh geometry={nodes.Iowa_0.geometry} material={materials.Orange} />
        </group>
        <group position={[-0.9, 0.46, 0]}>
          <mesh geometry={nodes.Kansas_0.geometry} material={materials.Yellow} />
        </group>
        <group position={[1.35, -0.18, 0]}>
          <mesh geometry={nodes.Kentucky_0.geometry} material={materials.Yellow} />
        </group>
        <group position={[0.49, -1.14, 0]}>
          <mesh geometry={nodes.Louisiana_0.geometry} material={materials.Yellow} />
        </group>
        <group position={[4.03, 2.14, 0]}>
          <mesh geometry={nodes.Maine_0.geometry} material={materials.Dark_green} />
        </group>
        <group position={[2.94, 0.61, 0.1]}>
          <mesh geometry={nodes.Maryland_0.geometry} material={materials.Orange} />
        </group>
        <group position={[3.84, 1.5, 0]}>
          <mesh geometry={nodes.Massachusetts_0.geometry} material={materials.Light_Green} />
        </group>
        <group position={[1, 1.95, 0]}>
          <mesh geometry={nodes.Michigan1_0.geometry} material={materials.Orange} />
        </group>
        <group position={[1.66, 0.92, 0]}>
          <mesh geometry={nodes.Michigan2_0.geometry} material={materials.Orange} />
        </group>
        <group position={[-0.05, 2.46, 0]}>
          <mesh geometry={nodes.Minnesota_0.geometry} material={materials.Dark_green} />
        </group>
        <group position={[1.2, -0.65, 0]}>
          <mesh geometry={nodes.Mississippi_0.geometry} material={materials.shit} />
        </group>
        <group position={[0.18, 0.56, 0]}>
          <mesh geometry={nodes.Missouri_0.geometry} material={materials.Light_Green} />
        </group>
        <group position={[-2.85, 2.77, 0]}>
          <mesh geometry={nodes.Montana_0.geometry} material={materials.Purple} />
        </group>
        <group position={[-1.18, 1.17, 0]}>
          <mesh geometry={nodes.Nebraska_0.geometry} material={materials.Purple} />
        </group>
        <group position={[-3.81, 1.38, 0]}>
          <mesh geometry={nodes.Nevada_0.geometry} material={materials.Light_Green} />
        </group>
        <group position={[3.97, 2.07, 0]}>
          <mesh geometry={nodes.New_Hampshire_0.geometry} material={materials.shit} />
        </group>
        <group position={[3.66, 1.14, 0]}>
          <mesh geometry={nodes.New_Jersey_0.geometry} material={materials.shit} />
        </group>
        <group position={[-2.18, -0.09, 0]}>
          <mesh geometry={nodes.New_Mexico_0.geometry} material={materials.Purple} />
        </group>
        <group position={[2.88, 1.42, 0]}>
          <mesh geometry={nodes.New_york_0.geometry} material={materials.Dark_green} />
        </group>
        <group position={[2.66, -0.15, 0]}>
          <mesh geometry={nodes.North_Carolina_0.geometry} material={materials.Orange} />
        </group>
        <group position={[-1.08, 2.51, 0]}>
          <mesh geometry={nodes.North_dakota_0.geometry} material={materials.Yellow} />
        </group>
        <group position={[1.99, 0.91, 0]}>
          <mesh geometry={nodes.Ohio_0.geometry} material={materials.Light_Green} />
        </group>
        <group position={[-1.12, -0.22, 0]}>
          <mesh geometry={nodes.Oklahoma_0.geometry} material={materials.shit} />
        </group>
        <group position={[-4.16, 2.47, 0]}>
          <mesh geometry={nodes.Oregon_0.geometry} material={materials.Orange} />
        </group>
        <group position={[2.68, 1.08, 0]}>
          <mesh geometry={nodes.Pennsylvania_0.geometry} material={materials.Yellow} />
        </group>
        <group position={[4.11, 1.4, 0]}>
          <mesh geometry={nodes.Rhode_island_0.geometry} material={materials.Purple} />
        </group>
        <group position={[2.46, -0.54, 0]}>
          <mesh geometry={nodes.South_Carolina_0.geometry} material={materials.Dark_green} />
        </group>
        <group position={[-1.13, 1.82, 0]}>
          <mesh geometry={nodes.South_Dakota_0.geometry} material={materials.shit} />
        </group>
        <group position={[1.3, -0.32, 0]}>
          <mesh geometry={nodes.Tennessee_0.geometry} material={materials.Purple} />
        </group>
        <group position={[-1.9, -1.27, 0]}>
          <mesh geometry={nodes.Texas_0.geometry} material={materials.Dark_green} />
        </group>
        <group position={[-2.85, 1.16, 0]}>
          <mesh geometry={nodes.Utah_0.geometry} material={materials.shit} />
        </group>
        <group position={[3.7, 2, 0]}>
          <mesh geometry={nodes.Vermont_0.geometry} material={materials.Orange} />
        </group>
        <group position={[2.6, 0.05, 0]}>
          <mesh geometry={nodes.Virginia_0.geometry} material={materials.Dark_green} />
        </group>
        <group position={[-3.84, 3, 0]}>
          <mesh geometry={nodes.Washington_0.geometry} material={materials.shit} />
        </group>
        <group position={[2.77, 0.58, 0]}>
          <mesh geometry={nodes.West_Virginia_0.geometry} material={materials.Purple} />
        </group>
        <group position={[0.73, 1.97, 0]}>
          <mesh geometry={nodes.Wisconsin_0.geometry} material={materials.Light_Green} />
        </group>
        <group position={[-2.26, 1.77, 0]}>
          <mesh geometry={nodes.Wyoming_0.geometry} material={materials.Dark_green} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/../scene_2.gltf')
