/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/../scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.52}>
        <group position={[-2.09, 0.81, 0]}>
          <mesh geometry={nodes.Colorado_0.geometry} material={materials.s_7} />
        </group>
        <group position={[0.02, 1.24, 0]}>
          <mesh geometry={nodes.Iowa_0.geometry} material={materials.s_6} />
        </group>
        <group position={[-0.9, 0.46, 0]}>
          <mesh geometry={nodes.Kansas_0.geometry} material={materials.s_8} />
        </group>
        <group position={[-0.05, 2.46, 0]}>
          <mesh geometry={nodes.Minnesota_0.geometry} material={materials.s_2} />
        </group>
        <group position={[0.18, 0.56, 0]}>
          <mesh geometry={nodes.Missouri_0.geometry} material={materials.s_9} />
        </group>
        <group position={[-1.18, 1.17, 0]}>
          <mesh geometry={nodes.Nebraska_0.geometry} material={materials.s_5} />
        </group>
        <group position={[-1.08, 2.51, 0]}>
          <mesh geometry={nodes.North_dakota_0.geometry} material={materials.s_1} />
        </group>
        <group position={[-1.13, 1.82, 0]}>
          <mesh geometry={nodes.South_Dakota_0.geometry} material={materials.s_3} />
        </group>
        <group position={[-2.26, 1.77, 0]}>
          <mesh geometry={nodes.Wyoming_0.geometry} material={materials.s_4} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/../scene.gltf')
